//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faktury
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElementFaktury
    {
        public string Id { get; set; }
        public decimal Ilosc { get; set; }
    
        public virtual Produkt Produkt { get; set; }
        public virtual Faktura Faktura { get; set; }
    }
}
