//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faktury
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faktura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faktura()
        {
            this.ElementFaktury = new HashSet<ElementFaktury>();
        }
    
        public int Id { get; set; }
        public string NumerFaktury { get; set; }
        public System.DateTime DataWystawienia { get; set; }
        public System.DateTime DataSprzedazy { get; set; }
    
        public virtual Kontrahent Kontrahent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementFaktury> ElementFaktury { get; set; }
        public virtual FormaZaplaty FormaZaplaty { get; set; }
    }
}
